### ISSUE TITLE
看完列表还是不知道如何选择

### ISSUE THREAD

**Issue by vincent4j** [hzlzh/AlfredWorkflow.com#20]
刚才去看来一下，workflow 是很多很多，但对于我一个新人来人，压根不知道哪个好哪个不好，我也无法「通过关键字」来检索查找。到最后我还是不知道具体安装哪个。

我自己的一点想法：
- 点赞：每个 flow 后面加个按钮，使用者觉得好就点赞，然后根据点赞个数排列。
- 排行榜：根据 hzlzh 对 flow 的喜欢程度，自己人为得给他排序。

**Comment by amio** [comment]
目测站点是静态的吧，点赞应该没法实现（but，facebook 的点赞按钮不知道能不能支持同一个页面里逐条点？）

排行榜的话，按 alfredworkflow.com 的定位来看是更希望突出中立立场，而非个人喜好，所以排行榜估计也不会做 ╮(╯_╰)╭

**Comment by hzlzh** [comment]
站点是动态的，知识用了 wp-super-cache 做静态。
排行一直没抽出时间做。

**Comment by imqianxun** [comment]
可能需要分类，以方便更快的查找。

不过看列表之前不是应该先想清楚自己需要用哪些功能再去扫列表么？
