### ISSUE TITLE
Site contains Malware

### ISSUE THREAD

**Issue by Luzifer** [hzlzh/AlfredWorkflow.com#27]
- As a user I want to trust the directory I'm accessing to download workflows I'm going to install in Alfred. 
- As a developer I want to be sure my workflows are in a clean and sane environment and get not mixed with malware.

Sadly the [Safe Browsing Advisory](https://www.google.com/safebrowsing/diagnostic?site=http%3A%2F%2Fwww.alfredworkflow.com%2F&client=googlechrome&hl=en-US) lists the website as a source for malware.

![screen shot 2015-05-03 at 00 50 12](https://cloud.githubusercontent.com/assets/20142/7443037/9414a92a-f12e-11e4-9c3b-3f6ebc83d8da.png)

**Comment by brianroach** [comment]
no bueno.

**Comment by hzlzh** [comment]
Under Maintenance now

**Comment by hzlzh** [comment]
fixed
