### ISSUE TITLE
总是优先显示搜索结果而不是workflow的结果

### ISSUE THREAD

**Issue by thinkxf** [hzlzh/AlfredWorkflow.com#29]
遇到一个问题总是解决不了, 我调出alfred, 输入 `dash array` , 显示的结果类似于这样:

```
search Google for 'dash array'
search Amazon for 'dash array'
search Wikipedia for 'dash array'
```
非常疑惑为什么会显示搜索的结果而不是dash的搜索结果, 试着在dash中搜索了一下, 是有内容的,  另外,我的好多workflow都有这样的问题, 尝试重新安装仍然解决不了问题, 希望了解的能帮忙看下什么原因, 谢谢.

**Comment by SSCedric** [comment]
确保你脚本运行正常，并且输出的是alfred要求的xml格式
