### ISSUE TITLE
http://www.alfredworkflow.com/  download from backup 500

### ISSUE THREAD

**Issue by tl3shi** [hzlzh/AlfredWorkflow.com#34]
RT 

 
>
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, hzlzh.mail@gmail.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Apache Server at www.alfredworkflow.com Port 80

**Comment by hzlzh** [comment]
known issue
