### ISSUE TITLE
网站好像出问题了。。

### ISSUE THREAD

**Issue by Laily123** [hzlzh/AlfredWorkflow.com#44]

**Comment by forecho** [comment]
网站下载不了

**Comment by hzlzh** [comment]
下载功能目前停用，可以在 github 上直接下载
https://github.com/hzlzh/AlfredWorkflow.com/tree/master/Downloads/Workflows

**Comment by forecho** [comment]
对不上号，下载特定的某一个插件要找半天

**Comment by jimhan** [comment]
你好，那个 submit 功能好像不能用了，报错 500 。

**Comment by hzlzh** [comment]
@jimhan 请 Fork 项目之后使用  https://github.com/hzlzh/AlfredWorkflow.com/pulls 功能提交到库里
